### PR TITLE
Feature/server

### PR DESCRIPTION
**Pull request by van-hsieh**
All server routes for connecting to apis, handling body and query parameter.

### CODE REVIEW

**Comment by van-hsieh** [comment]
@cdeng1111 Could you please review the pull request and let me know what to update?

**Review by fernanda1411 — COMMENTED** [review]
Fantastic work!!! 

Can we add a `.env.sample` on the root that is not on `.gitignore` where we can add the keys with dummy values? That would make it easier for us to setup our own `.env` files when cloning this repo. 

example:

.env.sample
```
#.env file
GITHUB_TOKEN =your_github_token
```
________________

Also, I'm not sure, but I think our server endpoints won't necessary map one to one with the API provided to us and instead it will have endpoints specific to the need of our components. Our endpoints might have to communicate with more than one of the provided API endpoints to get certain things. This is just a though and I won't ask for changes, but I think we should keep that in mind.

**Comment by van-hsieh** [comment]
@fernanda1411 Great feedback like always. Added the .env.sample file to the root directory.

For the server routes, I wrote it modularly so client side can pick and choose what it needs.

**Review by cdeng1111 — APPROVED** [review]
great job! looks good to me.

**Comment by van-hsieh** [comment]
Merged with this commit - d450cdd0f2170279cf1bcde65078d0f5d8f8e3db
Merged locally and bypassed pull request.

**Pull request closed without merging**
